require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 15

RSpec/MessageSpies:
  Enabled: false # Some specs require have_received, some receive

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
