require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/spiders/**/*'

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 18
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/**/*'

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/views/**/*'

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 10
  Exclude:
    - 'spec/views/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
