require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable


Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/**/*'

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
