require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
